/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FeedRouteRouteImport } from './routes/_feed/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as FeedIndexRouteImport } from './routes/_feed/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as ProfileUsernameIndexRouteImport } from './routes/profile.$username.index'
import { Route as ProfileUsernameLikesRouteImport } from './routes/profile.$username.likes'
import { Route as ProfileUsernameEditRouteImport } from './routes/profile.$username.edit'
import { Route as ProfileUsernameBookmarksRouteImport } from './routes/profile.$username.bookmarks'
import { Route as PostsPostIdEditRouteImport } from './routes/posts/$postId.edit'
import { Route as FeedPostsNewRouteImport } from './routes/_feed/posts.new'
import { Route as ProfileUsernamePostIdModalRouteImport } from './routes/profile.$username.$postId.modal'
import { Route as FeedPostsPostIdModalRouteImport } from './routes/_feed/posts.$postId.modal'

const FeedRouteRoute = FeedRouteRouteImport.update({
  id: '/_feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIndexRoute = FeedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeedRouteRoute,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameIndexRoute = ProfileUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileUsernameRoute,
} as any)
const ProfileUsernameLikesRoute = ProfileUsernameLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => ProfileUsernameRoute,
} as any)
const ProfileUsernameEditRoute = ProfileUsernameEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileUsernameRoute,
} as any)
const ProfileUsernameBookmarksRoute =
  ProfileUsernameBookmarksRouteImport.update({
    id: '/bookmarks',
    path: '/bookmarks',
    getParentRoute: () => ProfileUsernameRoute,
  } as any)
const PostsPostIdEditRoute = PostsPostIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PostsPostIdRoute,
} as any)
const FeedPostsNewRoute = FeedPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => FeedRouteRoute,
} as any)
const ProfileUsernamePostIdModalRoute =
  ProfileUsernamePostIdModalRouteImport.update({
    id: '/$postId/modal',
    path: '/$postId/modal',
    getParentRoute: () => ProfileUsernameRoute,
  } as any)
const FeedPostsPostIdModalRoute = FeedPostsPostIdModalRouteImport.update({
  id: '/posts/$postId/modal',
  path: '/posts/$postId/modal',
  getParentRoute: () => FeedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof FeedIndexRoute
  '/auth/register': typeof AuthRegisterRoute
  '/posts/$postId': typeof PostsPostIdRouteWithChildren
  '/profile/$username': typeof ProfileUsernameRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/posts/new': typeof FeedPostsNewRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
  '/profile/$username/bookmarks': typeof ProfileUsernameBookmarksRoute
  '/profile/$username/edit': typeof ProfileUsernameEditRoute
  '/profile/$username/likes': typeof ProfileUsernameLikesRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
  '/posts/$postId/modal': typeof FeedPostsPostIdModalRoute
  '/profile/$username/$postId/modal': typeof ProfileUsernamePostIdModalRoute
}
export interface FileRoutesByTo {
  '/auth/register': typeof AuthRegisterRoute
  '/posts/$postId': typeof PostsPostIdRouteWithChildren
  '/': typeof FeedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/posts/new': typeof FeedPostsNewRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
  '/profile/$username/bookmarks': typeof ProfileUsernameBookmarksRoute
  '/profile/$username/edit': typeof ProfileUsernameEditRoute
  '/profile/$username/likes': typeof ProfileUsernameLikesRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
  '/posts/$postId/modal': typeof FeedPostsPostIdModalRoute
  '/profile/$username/$postId/modal': typeof ProfileUsernamePostIdModalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_feed': typeof FeedRouteRouteWithChildren
  '/auth/register': typeof AuthRegisterRoute
  '/posts/$postId': typeof PostsPostIdRouteWithChildren
  '/profile/$username': typeof ProfileUsernameRouteWithChildren
  '/_feed/': typeof FeedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_feed/posts/new': typeof FeedPostsNewRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
  '/profile/$username/bookmarks': typeof ProfileUsernameBookmarksRoute
  '/profile/$username/edit': typeof ProfileUsernameEditRoute
  '/profile/$username/likes': typeof ProfileUsernameLikesRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
  '/_feed/posts/$postId/modal': typeof FeedPostsPostIdModalRoute
  '/profile/$username/$postId/modal': typeof ProfileUsernamePostIdModalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/register'
    | '/posts/$postId'
    | '/profile/$username'
    | '/auth/'
    | '/posts/new'
    | '/posts/$postId/edit'
    | '/profile/$username/bookmarks'
    | '/profile/$username/edit'
    | '/profile/$username/likes'
    | '/profile/$username/'
    | '/posts/$postId/modal'
    | '/profile/$username/$postId/modal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/register'
    | '/posts/$postId'
    | '/'
    | '/auth'
    | '/posts/new'
    | '/posts/$postId/edit'
    | '/profile/$username/bookmarks'
    | '/profile/$username/edit'
    | '/profile/$username/likes'
    | '/profile/$username'
    | '/posts/$postId/modal'
    | '/profile/$username/$postId/modal'
  id:
    | '__root__'
    | '/_feed'
    | '/auth/register'
    | '/posts/$postId'
    | '/profile/$username'
    | '/_feed/'
    | '/auth/'
    | '/_feed/posts/new'
    | '/posts/$postId/edit'
    | '/profile/$username/bookmarks'
    | '/profile/$username/edit'
    | '/profile/$username/likes'
    | '/profile/$username/'
    | '/_feed/posts/$postId/modal'
    | '/profile/$username/$postId/modal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FeedRouteRoute: typeof FeedRouteRouteWithChildren
  AuthRegisterRoute: typeof AuthRegisterRoute
  PostsPostIdRoute: typeof PostsPostIdRouteWithChildren
  ProfileUsernameRoute: typeof ProfileUsernameRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_feed': {
      id: '/_feed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FeedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_feed/': {
      id: '/_feed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FeedIndexRouteImport
      parentRoute: typeof FeedRouteRoute
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/': {
      id: '/profile/$username/'
      path: '/'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof ProfileUsernameIndexRouteImport
      parentRoute: typeof ProfileUsernameRoute
    }
    '/profile/$username/likes': {
      id: '/profile/$username/likes'
      path: '/likes'
      fullPath: '/profile/$username/likes'
      preLoaderRoute: typeof ProfileUsernameLikesRouteImport
      parentRoute: typeof ProfileUsernameRoute
    }
    '/profile/$username/edit': {
      id: '/profile/$username/edit'
      path: '/edit'
      fullPath: '/profile/$username/edit'
      preLoaderRoute: typeof ProfileUsernameEditRouteImport
      parentRoute: typeof ProfileUsernameRoute
    }
    '/profile/$username/bookmarks': {
      id: '/profile/$username/bookmarks'
      path: '/bookmarks'
      fullPath: '/profile/$username/bookmarks'
      preLoaderRoute: typeof ProfileUsernameBookmarksRouteImport
      parentRoute: typeof ProfileUsernameRoute
    }
    '/posts/$postId/edit': {
      id: '/posts/$postId/edit'
      path: '/edit'
      fullPath: '/posts/$postId/edit'
      preLoaderRoute: typeof PostsPostIdEditRouteImport
      parentRoute: typeof PostsPostIdRoute
    }
    '/_feed/posts/new': {
      id: '/_feed/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof FeedPostsNewRouteImport
      parentRoute: typeof FeedRouteRoute
    }
    '/profile/$username/$postId/modal': {
      id: '/profile/$username/$postId/modal'
      path: '/$postId/modal'
      fullPath: '/profile/$username/$postId/modal'
      preLoaderRoute: typeof ProfileUsernamePostIdModalRouteImport
      parentRoute: typeof ProfileUsernameRoute
    }
    '/_feed/posts/$postId/modal': {
      id: '/_feed/posts/$postId/modal'
      path: '/posts/$postId/modal'
      fullPath: '/posts/$postId/modal'
      preLoaderRoute: typeof FeedPostsPostIdModalRouteImport
      parentRoute: typeof FeedRouteRoute
    }
  }
}

interface FeedRouteRouteChildren {
  FeedIndexRoute: typeof FeedIndexRoute
  FeedPostsNewRoute: typeof FeedPostsNewRoute
  FeedPostsPostIdModalRoute: typeof FeedPostsPostIdModalRoute
}

const FeedRouteRouteChildren: FeedRouteRouteChildren = {
  FeedIndexRoute: FeedIndexRoute,
  FeedPostsNewRoute: FeedPostsNewRoute,
  FeedPostsPostIdModalRoute: FeedPostsPostIdModalRoute,
}

const FeedRouteRouteWithChildren = FeedRouteRoute._addFileChildren(
  FeedRouteRouteChildren,
)

interface PostsPostIdRouteChildren {
  PostsPostIdEditRoute: typeof PostsPostIdEditRoute
}

const PostsPostIdRouteChildren: PostsPostIdRouteChildren = {
  PostsPostIdEditRoute: PostsPostIdEditRoute,
}

const PostsPostIdRouteWithChildren = PostsPostIdRoute._addFileChildren(
  PostsPostIdRouteChildren,
)

interface ProfileUsernameRouteChildren {
  ProfileUsernameBookmarksRoute: typeof ProfileUsernameBookmarksRoute
  ProfileUsernameEditRoute: typeof ProfileUsernameEditRoute
  ProfileUsernameLikesRoute: typeof ProfileUsernameLikesRoute
  ProfileUsernameIndexRoute: typeof ProfileUsernameIndexRoute
  ProfileUsernamePostIdModalRoute: typeof ProfileUsernamePostIdModalRoute
}

const ProfileUsernameRouteChildren: ProfileUsernameRouteChildren = {
  ProfileUsernameBookmarksRoute: ProfileUsernameBookmarksRoute,
  ProfileUsernameEditRoute: ProfileUsernameEditRoute,
  ProfileUsernameLikesRoute: ProfileUsernameLikesRoute,
  ProfileUsernameIndexRoute: ProfileUsernameIndexRoute,
  ProfileUsernamePostIdModalRoute: ProfileUsernamePostIdModalRoute,
}

const ProfileUsernameRouteWithChildren = ProfileUsernameRoute._addFileChildren(
  ProfileUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  FeedRouteRoute: FeedRouteRouteWithChildren,
  AuthRegisterRoute: AuthRegisterRoute,
  PostsPostIdRoute: PostsPostIdRouteWithChildren,
  ProfileUsernameRoute: ProfileUsernameRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
