/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FeedRouteRouteImport } from './routes/_feed/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as FeedIndexRouteImport } from './routes/_feed/index'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as ProfileUserIdIndexRouteImport } from './routes/profile.$userId.index'
import { Route as ProfileUserIdLikesRouteImport } from './routes/profile.$userId.likes'
import { Route as ProfileUserIdEditRouteImport } from './routes/profile.$userId.edit'
import { Route as ProfileUserIdBookmarksRouteImport } from './routes/profile.$userId.bookmarks'
import { Route as PostsPostIdEditRouteImport } from './routes/posts/$postId.edit'
import { Route as FeedPostsNewRouteImport } from './routes/_feed/posts.new'
import { Route as ProfileUserIdPostIdModalRouteImport } from './routes/profile.$userId.$postId.modal'
import { Route as FeedPostsPostIdModalRouteImport } from './routes/_feed/posts.$postId.modal'

const FeedRouteRoute = FeedRouteRouteImport.update({
  id: '/_feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIndexRoute = FeedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeedRouteRoute,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdIndexRoute = ProfileUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileUserIdRoute,
} as any)
const ProfileUserIdLikesRoute = ProfileUserIdLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => ProfileUserIdRoute,
} as any)
const ProfileUserIdEditRoute = ProfileUserIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileUserIdRoute,
} as any)
const ProfileUserIdBookmarksRoute = ProfileUserIdBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => ProfileUserIdRoute,
} as any)
const PostsPostIdEditRoute = PostsPostIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PostsPostIdRoute,
} as any)
const FeedPostsNewRoute = FeedPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => FeedRouteRoute,
} as any)
const ProfileUserIdPostIdModalRoute =
  ProfileUserIdPostIdModalRouteImport.update({
    id: '/$postId/modal',
    path: '/$postId/modal',
    getParentRoute: () => ProfileUserIdRoute,
  } as any)
const FeedPostsPostIdModalRoute = FeedPostsPostIdModalRouteImport.update({
  id: '/posts/$postId/modal',
  path: '/posts/$postId/modal',
  getParentRoute: () => FeedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof FeedIndexRoute
  '/auth/register': typeof AuthRegisterRoute
  '/posts/$postId': typeof PostsPostIdRouteWithChildren
  '/profile/$userId': typeof ProfileUserIdRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/posts/new': typeof FeedPostsNewRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
  '/profile/$userId/bookmarks': typeof ProfileUserIdBookmarksRoute
  '/profile/$userId/edit': typeof ProfileUserIdEditRoute
  '/profile/$userId/likes': typeof ProfileUserIdLikesRoute
  '/profile/$userId/': typeof ProfileUserIdIndexRoute
  '/posts/$postId/modal': typeof FeedPostsPostIdModalRoute
  '/profile/$userId/$postId/modal': typeof ProfileUserIdPostIdModalRoute
}
export interface FileRoutesByTo {
  '/auth/register': typeof AuthRegisterRoute
  '/posts/$postId': typeof PostsPostIdRouteWithChildren
  '/': typeof FeedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/posts/new': typeof FeedPostsNewRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
  '/profile/$userId/bookmarks': typeof ProfileUserIdBookmarksRoute
  '/profile/$userId/edit': typeof ProfileUserIdEditRoute
  '/profile/$userId/likes': typeof ProfileUserIdLikesRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
  '/posts/$postId/modal': typeof FeedPostsPostIdModalRoute
  '/profile/$userId/$postId/modal': typeof ProfileUserIdPostIdModalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_feed': typeof FeedRouteRouteWithChildren
  '/auth/register': typeof AuthRegisterRoute
  '/posts/$postId': typeof PostsPostIdRouteWithChildren
  '/profile/$userId': typeof ProfileUserIdRouteWithChildren
  '/_feed/': typeof FeedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_feed/posts/new': typeof FeedPostsNewRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
  '/profile/$userId/bookmarks': typeof ProfileUserIdBookmarksRoute
  '/profile/$userId/edit': typeof ProfileUserIdEditRoute
  '/profile/$userId/likes': typeof ProfileUserIdLikesRoute
  '/profile/$userId/': typeof ProfileUserIdIndexRoute
  '/_feed/posts/$postId/modal': typeof FeedPostsPostIdModalRoute
  '/profile/$userId/$postId/modal': typeof ProfileUserIdPostIdModalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/register'
    | '/posts/$postId'
    | '/profile/$userId'
    | '/auth/'
    | '/posts/new'
    | '/posts/$postId/edit'
    | '/profile/$userId/bookmarks'
    | '/profile/$userId/edit'
    | '/profile/$userId/likes'
    | '/profile/$userId/'
    | '/posts/$postId/modal'
    | '/profile/$userId/$postId/modal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/register'
    | '/posts/$postId'
    | '/'
    | '/auth'
    | '/posts/new'
    | '/posts/$postId/edit'
    | '/profile/$userId/bookmarks'
    | '/profile/$userId/edit'
    | '/profile/$userId/likes'
    | '/profile/$userId'
    | '/posts/$postId/modal'
    | '/profile/$userId/$postId/modal'
  id:
    | '__root__'
    | '/_feed'
    | '/auth/register'
    | '/posts/$postId'
    | '/profile/$userId'
    | '/_feed/'
    | '/auth/'
    | '/_feed/posts/new'
    | '/posts/$postId/edit'
    | '/profile/$userId/bookmarks'
    | '/profile/$userId/edit'
    | '/profile/$userId/likes'
    | '/profile/$userId/'
    | '/_feed/posts/$postId/modal'
    | '/profile/$userId/$postId/modal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FeedRouteRoute: typeof FeedRouteRouteWithChildren
  AuthRegisterRoute: typeof AuthRegisterRoute
  PostsPostIdRoute: typeof PostsPostIdRouteWithChildren
  ProfileUserIdRoute: typeof ProfileUserIdRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_feed': {
      id: '/_feed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FeedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_feed/': {
      id: '/_feed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FeedIndexRouteImport
      parentRoute: typeof FeedRouteRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId/': {
      id: '/profile/$userId/'
      path: '/'
      fullPath: '/profile/$userId/'
      preLoaderRoute: typeof ProfileUserIdIndexRouteImport
      parentRoute: typeof ProfileUserIdRoute
    }
    '/profile/$userId/likes': {
      id: '/profile/$userId/likes'
      path: '/likes'
      fullPath: '/profile/$userId/likes'
      preLoaderRoute: typeof ProfileUserIdLikesRouteImport
      parentRoute: typeof ProfileUserIdRoute
    }
    '/profile/$userId/edit': {
      id: '/profile/$userId/edit'
      path: '/edit'
      fullPath: '/profile/$userId/edit'
      preLoaderRoute: typeof ProfileUserIdEditRouteImport
      parentRoute: typeof ProfileUserIdRoute
    }
    '/profile/$userId/bookmarks': {
      id: '/profile/$userId/bookmarks'
      path: '/bookmarks'
      fullPath: '/profile/$userId/bookmarks'
      preLoaderRoute: typeof ProfileUserIdBookmarksRouteImport
      parentRoute: typeof ProfileUserIdRoute
    }
    '/posts/$postId/edit': {
      id: '/posts/$postId/edit'
      path: '/edit'
      fullPath: '/posts/$postId/edit'
      preLoaderRoute: typeof PostsPostIdEditRouteImport
      parentRoute: typeof PostsPostIdRoute
    }
    '/_feed/posts/new': {
      id: '/_feed/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof FeedPostsNewRouteImport
      parentRoute: typeof FeedRouteRoute
    }
    '/profile/$userId/$postId/modal': {
      id: '/profile/$userId/$postId/modal'
      path: '/$postId/modal'
      fullPath: '/profile/$userId/$postId/modal'
      preLoaderRoute: typeof ProfileUserIdPostIdModalRouteImport
      parentRoute: typeof ProfileUserIdRoute
    }
    '/_feed/posts/$postId/modal': {
      id: '/_feed/posts/$postId/modal'
      path: '/posts/$postId/modal'
      fullPath: '/posts/$postId/modal'
      preLoaderRoute: typeof FeedPostsPostIdModalRouteImport
      parentRoute: typeof FeedRouteRoute
    }
  }
}

interface FeedRouteRouteChildren {
  FeedIndexRoute: typeof FeedIndexRoute
  FeedPostsNewRoute: typeof FeedPostsNewRoute
  FeedPostsPostIdModalRoute: typeof FeedPostsPostIdModalRoute
}

const FeedRouteRouteChildren: FeedRouteRouteChildren = {
  FeedIndexRoute: FeedIndexRoute,
  FeedPostsNewRoute: FeedPostsNewRoute,
  FeedPostsPostIdModalRoute: FeedPostsPostIdModalRoute,
}

const FeedRouteRouteWithChildren = FeedRouteRoute._addFileChildren(
  FeedRouteRouteChildren,
)

interface PostsPostIdRouteChildren {
  PostsPostIdEditRoute: typeof PostsPostIdEditRoute
}

const PostsPostIdRouteChildren: PostsPostIdRouteChildren = {
  PostsPostIdEditRoute: PostsPostIdEditRoute,
}

const PostsPostIdRouteWithChildren = PostsPostIdRoute._addFileChildren(
  PostsPostIdRouteChildren,
)

interface ProfileUserIdRouteChildren {
  ProfileUserIdBookmarksRoute: typeof ProfileUserIdBookmarksRoute
  ProfileUserIdEditRoute: typeof ProfileUserIdEditRoute
  ProfileUserIdLikesRoute: typeof ProfileUserIdLikesRoute
  ProfileUserIdIndexRoute: typeof ProfileUserIdIndexRoute
  ProfileUserIdPostIdModalRoute: typeof ProfileUserIdPostIdModalRoute
}

const ProfileUserIdRouteChildren: ProfileUserIdRouteChildren = {
  ProfileUserIdBookmarksRoute: ProfileUserIdBookmarksRoute,
  ProfileUserIdEditRoute: ProfileUserIdEditRoute,
  ProfileUserIdLikesRoute: ProfileUserIdLikesRoute,
  ProfileUserIdIndexRoute: ProfileUserIdIndexRoute,
  ProfileUserIdPostIdModalRoute: ProfileUserIdPostIdModalRoute,
}

const ProfileUserIdRouteWithChildren = ProfileUserIdRoute._addFileChildren(
  ProfileUserIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  FeedRouteRoute: FeedRouteRouteWithChildren,
  AuthRegisterRoute: AuthRegisterRoute,
  PostsPostIdRoute: PostsPostIdRouteWithChildren,
  ProfileUserIdRoute: ProfileUserIdRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
